# Finding a motif in DNA
# find position of where the substring/motif is equal to parts of the DNA

def motif(string, sub):
    positions =[]
    dnalength = len(string)
    motiflength = len(sub)

    difference = dnalength - motiflength + 1
    for i in range(0,difference):
        if string[i : motiflength] == sub:
            positions.append(i+1)
        motiflength += 1
    return positions

res = motif('CGCGCGAACGCTTCGAACGCGCGAACGCTAGTCGAACGCGCGAACGCCGAACGCCCGGCGAACGCTCGAACGCGCGAACGCTCGAACGCTGGCAAGCGAACGCGCGGCGAACGCCGCGAACGCTCGAACGCACGAACGCCGAACGCACGAACGCTAACGAACGCGCCTTTCCGAACGCATCGAACGCGTCGAACGCAGCCTCGAACGCCGAACGCGACCGAACGCCGAACGCAGGAGCAAAACACCGCGAACGCTCCGAACGCTGGGCGAACGCGTCACGAACGCACGAACGCCGAACGCCGTTTGGGCGAACGCTATTTGACGAACGCCGAACGCACCGAACGCGCATGCGAACGCGGTTCGACCCGAACGCCACGCCTCCGAACGCACGAACGCCGAACGCCGAACGCGAGTGAGGACGAACGCCGAACGCAATCCGAACGCGTTATTCGAACGCTCGAACGCTGCGAACGCCGAACGCGCGAACGCTCGAACGCCCGAACGCACGAACGCCGAACGCCGAACGCCGAACGCAAGCCGAACGCGGTTGACGAACGCTTTGTGCGAACGCCCCCCGAACGCTCGAACGCAAACGAACGCCACATCGAACGCCCGAACGCGAGGGGTACGAACGCACCGAACGCCTACGAACGCCGAACGCATCGAACGCCGAACGCCCTACCGAACGCCGAACGCTCGAACGCGGCGAACGCTGTACGAACGCTTACCGCGAACGCTCGAACGCCGAACGCACTCCGAACGCATACGAACGCGCATAACGAACGCCGAACGCTGATGGCGAACGCCGAACGCCGAACGCATACCGAACGCCGAACGCTACGAACGCGTGCGCGAACGCCAGCTCGAACGCCCGAACGCCGAACGCCGCCGAACGCCGAACGCATCGAACGCGCCGAACGCGACGAACGCCGAACGCTTGGAGTCCCCCGAACGCCGAGTTGTGATACGAACGCCTTTCCGAACGC','CGAACGCCG')
for i in res:
    print(i, end=' ')
